name: Clang Tests with SonarScanner

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'
    paths:
      - 'clang/**'
      - '.github/workflows/clang-tests-sonar-cloud.yml'
      - '.github/workflows/llvm-project-tests-sonar-cloud.yml'
      - '!llvm/**'
  pull_request:
    branches:
      - 'release/**'
    paths:
      - 'clang/**'
      - '.github/workflows/clang-tests-sonar-cloud.yml'
      - '.github/workflows/llvm-project-tests-sonar-cloud.yml'
      - '!llvm/**'

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  check_clang:
    if: github.repository_owner == 'steakhal'
    name: Test clang,lldb,libclc
    uses: ./.github/workflows/llvm-project-tests-sonar-cloud.yml
    with:
      build_target: check-clang
      projects: clang;lldb;libclc
