name: Test libc++ rules

on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  checks: write

env:
  CMAKE: "/opt/bin/cmake"

# Comment
jobs:
  test-libcxx:
    name: "Test libcxx"
    runs-on: libcxx-runners-16
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
      - id: test-rule
        uses: EricWF/test-libcxx@v0.0
        with:
            config: "Generic-cxx23"
            cc: "clang"
            cxx: "clang++"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: |
            "**/test-results.xml"
            "**/*.abilist"

