# This file defines pre-commit CI for libc++, libc++abi, and libunwind (on Github).
#
# We split the configurations in multiple stages with the intent of saving compute time
# when a job fails early in the pipeline. This is why the jobs are marked as `continue-on-error: false`.
# We try to run the CI configurations with the most signal in the first stage.
#
# Stages 1 & 2 are meant to be "smoke tests", and are meant to catch most build/test failures quickly and without using
# too many resources.
# Stage 3 is "everything else", and is meant to catch breakages on more niche or unique configurations.
#
# Therefore, we "fail-fast" for any failures during stages 1 & 2, meaning any job failing cancels all other running jobs,
# under the assumption that if the "smoke tests" fail, then the other configurations will likely fail in the same way.
# However, stage 3 does not fail fast, as it's more likely that any one job failing is a flake or a configuration-specific
#
name: Build and Test libc++
on:
  pull_request:
    paths:
      - 'libcxx/**'
      - 'libcxxabi/**'
      - 'libunwind/**'
      - 'runtimes/**'
      - 'cmake/**'
      - '.github/workflows/libcxx-build-and-test.yaml'
  schedule:
    # Run nightly at 08:00 UTC (aka 00:00 Pacific, aka 03:00 Eastern)
    - cron: '0 8 * * *'

permissions:
  contents: read # Default everything to read-only

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  buildkite:
    runs-on: ubuntu-latest # Just triggering the pipeline, this doesn't matter
    steps:
      - name: "Trigger a Buildkite Build"
        uses: "buildkite/trigger-pipeline-action@v2.3.0"
        with:
          buildkite_api_access_token: ${{ secrets.LIBCXX_CI_BUILDKITE_PIPELINE_ACCESS_TOKEN }}
          pipeline: "llvm-project/libcxx-ci"
          branch: "main"
          commit: "HEAD"
          message:  ":github: Triggered from a GitHub Action"
          ignore_pipeline_branch_filter: true
          send_pull_request: true
          wait: true
          wait_interval: 10
          wait_timeout: 300
