name: "Check libc++ generated files"
on:
  pull_request:
    paths:
      - 'libcxx/**'

permissions:
  contents: read

jobs:
  check_generated_files:
    runs-on:
      group: libcxx-runners-1
    steps:
      - name: Fetch LLVM sources
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout through merge base
        uses: rmacklin/fetch-through-merge-base@v0
        with:
          base_ref: ${{ github.event.pull_request.base.ref }}
          head_ref: ${{ github.event.pull_request.head.sha }}
          deepen_length: 500

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          separator: ","
          skip_initial_fetch: true
      - name: Install Precommit Hooks
        run: bash ./libcxx/utils/formatting/install-formatting-hooks.sh --force

      - name: Setup the paths to check for formatting
        run: git config --local llvmPrecommit.formatPaths "libcxx"

      # Reset the git branch to have all of the modified files staged but not committed.
      - name: Reset git state
        run: git reset --soft origin/${{ github.base_ref }}

      - name: Check generated files
        run: bash ./libcxx/utils/formatting/pre-commit-formatting-hook.sh


      - name: Check generated files
        run: libcxx/utils/ci/run-buildbot check-generated-output
