name: Build and test llvm

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: create build dir
      run: mkdir _build
    - name: configure
      run: cmake ../llvm -DCMAKE_BUILD_TYPE=MinSizeRe -Thost=x64 -DLLVM_TARGETS_TO_BUILD=host -DLLVM_ENABLE_WARNINGS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF
      working-directory: _build 
    - name: build
      run: cmake --build .
      working-directory: _build
    - name: test
      run: cmake --build . --target check
      working-directory: _build
