name: 'Repo Lockdown'
on:
  pull_request_target:
    types: opened
    paths-ignore:
      - 'libcxx/**'
      - 'libcxxabi/**'
      - 'libunwind/**'
      - 'runtimes/**'
      - 'lldb/**'
      - '.github/**'
      - 'clang/lib/Format/**'
      - 'clang/include/clang/Format/**'
      - 'clang/docs/**'
      - 'clang/unitests/Format/**'
      - 'clang/tools/clang-format/**'
      - 'llvm/utils/git/**'

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    if: github.repository == 'llvm/llvm-project'
    steps:
      - name: Nothing
        run: |
          echo "Not running repo lockdown"
